### ISSUE TITLE
Leadership center layout 

### ISSUE THREAD

**Issue by StephenXie** [frc-7419/frc-7419.github.io#4]
Center the leadership grid(not individual cells). Currently, it's positioned to the left as shown below.
![image](https://user-images.githubusercontent.com/49465499/147707555-d2d066f4-b582-4799-9dd9-78ee820649b6.png)

**Comment by wlmchen** [comment]
![image](https://user-images.githubusercontent.com/65417452/147708569-2a1473f9-0d40-442a-848c-ab3fd2943664.png)

it is centered

**Comment by StephenXie** [comment]
I meant centered like this
![image](https://user-images.githubusercontent.com/49465499/147708798-f0c8d1f9-2afb-4dc4-a176-10b67cda83b9.png)

**Comment by StephenXie** [comment]
It feels a bit off when it's leaning towards the left

**Comment by StephenXie** [comment]
Fixed with [commit](https://github.com/frc-7419/frc-7419.github.io/commit/4b6722058c80b6bb333d9f805952210e04f787a7)
